version: '3.8'

services:
  # Web server container
  web:
    image: nginx:alpine
    container_name: test-web
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    restart: unless-stopped

  # API server container  
  api:
    image: node:18-alpine
    container_name: test-api
    command: ["sleep", "3600"]
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    restart: unless-stopped

  # Database container
  database:
    image: postgres:15-alpine
    container_name: test-database
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: testuser
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Cache/Redis container
  redis:
    image: redis:7-alpine
    container_name: test-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # Additional service to create more containers in the group
  worker:
    image: alpine:latest
    container_name: test-worker
    command: ["sleep", "3600"]
    environment:
      - WORKER_TYPE=background
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: