name: '[CI] Quick Checks'

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'tickets/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quick-checks:
    name: Quick Checks
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Setup Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install tauri-deps
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libgirepository1.0-dev \
          libglib2.0-dev \
          libgtk-3-dev \
          libgdk-pixbuf2.0-dev \
          libcairo2-dev \
          libpango1.0-dev \
          libatk1.0-dev \
          libwebkit2gtk-4.0-dev \
          libwebkit2gtk-4.1-dev \
          libjavascriptcoregtk-4.1-dev \
          libappindicator3-dev \
          librsvg2-dev \
          patchelf \
          pkg-config \
          libssl-dev

    - name: Install dependencies
      run: |
        npm ci
        cd src-tauri
        cargo fetch

    - name: Lint frontend
      run: npm run lint

    - name: Type check frontend
      run: npm run type-check

    - name: Rust format check
      run: |
        cd src-tauri
        cargo fmt -- --check

    - name: Rust clippy check
      run: |
        cd src-tauri
        cargo clippy -- -D warnings
